### ISSUE TITLE
voot asking for premium even tho i have premium sub

### ISSUE THREAD

**Issue by karthikfiretv** [Vikassm73/AjaykRepo#114]
voot asking for premium even tho i have premium sub , why is this? thanks for help

**Comment by Vikassm73** [comment]
Install below addon

Enable Debug logging and run the addon

Do Clear log. After that try to play premium content.

On failure, send me the debug log on 

vikassm73@gmail.com

[plugin.video.voot.zip](https://github.com/Vikassm73/AjaykRepo/files/10001200/plugin.video.voot.zip)

**Comment by iamnewtogithubhelpme** [comment]
I too have started facing this issue today. What is the fix? Can you please tell? Will the new plugin zip help?

**Comment by Vikassm73** [comment]
Read above comment and send me a debug log as mentioned above. I will check it on Monday

**Comment by iamnewtogithubhelpme** [comment]
Just to update. It seems that issue is with one single episode of bigg boss (i didn't try any other show). I checked voot app and logged in with an account which doesnt have subscription and all episodes of bigg boss are playable. Even latest episode is available without subscription.

Btw i tried a movie which would never work without subscription and in addon too is playable (with my subscription added of.course). So issue seems to be specific videos and not across voot.
