### ISSUE TITLE
Sonyliv giving error

### ISSUE THREAD

**Issue by rishi684** [Vikassm73/AjaykRepo#9]
On playing tv series on sonyliv they giving error
![Screenshot_2021-06-06-19-33-28-618_org xbmc kodi](https://user-images.githubusercontent.com/84761860/120927339-48c82080-c6fe-11eb-8687-50361e3cbdce.jpg)

**Comment by Vikassm73** [comment]
are you using Kodi Matrix? this is working fine in Leia.

**Comment by Vikassm73** [comment]
Correction done, Please check now

**Comment by rishi684** [comment]
Yes using kodi 19.1 version..

**Comment by rishi684** [comment]
Same error occurs.. when new update for kodi matrix

**Comment by YeahArun** [comment]
> Correction done, Please check now

Thanks, It is working now. But there are segmenst that still has problems specially on hollywood movies. 
Also the interface looks like a trimmed version of Sonylive. All options like sonyliv sports and originals are not there. May be because of the subscription. I use kodi as its a single interface, forward rewind stop etc are same in case I use Netflix, hotstar, amazon etc else they have their own methodology.
Is there a possibolity of getting all options for the subscribed users of Sonyliv? 

In any case thanks for putting your time and effort on this.

**Comment by Vikassm73** [comment]
Those which required subscription are not working.
